# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: inmydelorean
email: inmydelorean@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Hello World! I'm a QA Engineer from Ukraine.
  Actually I use this site to train my git and all other skills.
  So if you see all this mess around please don't be confused.
  Anyway if you reading this I wash you all the best.
  May the force be with you!
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: inmydelorean
github_username:  inmydelorean

# Build settings
markdown: kramdown

theme: jekyll-theme-hacker